from my_commands.imports import *

BRING = utilities.load_toml_relative("config/bringme.toml")

Breathe.add_commands(
    AppContext("chrome"),
    {
        "[new] incognito window": Key("cs-n"),
        "new tab [<n>]": Key("c-t:%(n)s"),
        "next tab [<n>]": Key("c-tab:%(n)s"),
        "previous tab [<n>]": Key("cs-tab:%(n)s"),
        "close tab [<n>]": Key("c-w/5:%(n)s"),
        "reopen tab [<n>]": Key("cs-t:%(n)s"),
        "<numberth> tab": Key("c-%(numberth)s"),
        "page back [<n>]": Key("a-left:%(n)s"),
        "page forward [<n>]": Key("a-right:%(n)s"),
        "zoom reset": Key("c-0"),
        "refresh": Key("c-f5"),
        "switch focus [<n>]": Key("f6:%(n)s"),
        "find <text>": Key("c-f/20") + Text("%(text)s"),
        "[find] next match [<n>]": Key("c-g:%(n)s"),
        "[find] prior match [<n>]": Key("cs-g:%(n)s"),
        "[toggle] caret browsing": Key("f7"),
        "home page": Key("a-home"),
        # "show history"            : Key("c-h"),
        "show history": Key("c-t") + Text("chrome://history/\n"),
        "google search": Key("c-l"),
        "show downloads": Key("c-j"),
        "add bookmark": Key("c-d"),
        "bookmark all tabs": Key("cs-d"),
        "[toggle] bookmark bar": Key("cs-b"),
        "show bookmarks": Key("cs-o"),
        "switch user": Key("cs-m"),
        "chrome task manager": Key("s-escape"),
        "[toggle] full screen": Key("f11"),
        "focus notification": Key("a-n"),
        "allow notification": Key("as-a"),
        "deny notification": Key("as-a"),
        "developer tools": Key("f12"),
        "view [page] source": Key("c-u"),
        "resume": Key("f8"),
        "step over": Key("f10"),
        "step into": Key("f11"),
        "step out": Key("s-f11"),
        "copy all": Key("c-a/20, c-c"),
        "go <site>": Key("c-l/10") + Text("%(site)s") + Key("enter"),
        "search <text>": Key("c-l/10") + Text("%(text)s") + Key("enter"),
        "science hub":
        # Key("a-d") + Store() + Key("delete") + Text("https://sci-hub.tw/") + Retrieve() + Key("enter"),
        Key("c-l/10, left/10") + Text("https://sci-hub.tw/") + Key("enter"),
        "save image": Function(utilities.chrome_save_image),
        # Surfing
        "(toggle) surfing keys": Key("a-s"),
        "split right": Key("w-left/50, W/50, w-right"),
        "duplicate tab": Key("y, t"),
        "go to root": Key("g, U"),
        "scroll left [<n>]": Key("h:%(n)s"),
        "scroll right [<n>]": Key("l:%(n)s"),
    },
    [
        Choice("site", BRING["website"]),
        Choice(
            "numberth",
            {
                "first": "1",
                "second": "2",
                "third": "3",
                "fourth": "4",
                "fifth": "5",
                "sixth": "6",
                "seventh": "7",
                "eighth": "8",
                "(last | ninth)": "9",
                "next": "pgdown",
                "previous": "pgup",
            },
        ),
    ],
    # ccr=False
)
